-- Constraints for ORDERS
ALTER TABLE COLLECTIBLE_DIECAST.ORDERS
ADD CONSTRAINT PK_ORDERNUMBER PRIMARY KEY (orderNumber),
ADD CONSTRAINT FK_CUSTOMERNUMBER FOREIGN KEY (customerNumber) REFERENCES ADO_GROUP3_DB.COLLECTIBLE_DIECAST.CUSTOMERS(customerNumber),
ADD CONSTRAINT FK_EMPLOYEENUMBER FOREIGN KEY (employeeNumber) REFERENCES ADO_GROUP3_DB.COLLECTIBLE_DIECAST.EMPLOYEES(employeeNumber),
ADD CONSTRAINT FK_MODEID FOREIGN KEY (modeID) REFERENCES ADO_GROUP3_DB.COLLECTIBLE_DIECAST.SHIPMENT_MODE(modeID);

-- Constraints for ORDER_DETAILS
ALTER TABLE COLLECTIBLE_DIECAST.ORDER_DETAILS
ADD CONSTRAINT PK_OFFICECODE PRIMARY KEY (officecode),
ADD CONSTRAINT FK_EMPLOYEENUMBER FOREIGN KEY (employeeNumber) REFERENCES ADO_GROUP3_DB.COLLECTIBLE_DIECAST.EMPLOYEES(employeeNumber);

-- Constraints for VENDORS
ALTER TABLE COLLECTIBLE_DIECAST.VENDORS 
ADD CONSTRAINT PK_VENDORS PRIMARY KEY (VENDORID);
