-- Constraints for ORDERS
ALTER TABLE COLLECTIBLE_DIECAST.ORDERS
ADD CONSTRAINT PK_ORDERNUMBER PRIMARY KEY (orderNumber),
ADD CONSTRAINT FK_CUSTOMERNUMBER FOREIGN KEY (customerNumber) REFERENCES ADO_GROUP3_DB.COLLECTIBLE_DIECAST.CUSTOMERS(customerNumber),
ADD CONSTRAINT FK_EMPLOYEENUMBER FOREIGN KEY (employeeNumber) REFERENCES ADO_GROUP3_DB.COLLECTIBLE_DIECAST.EMPLOYEES(employeeNumber),
ADD CONSTRAINT FK_MODEID FOREIGN KEY (modeID) REFERENCES ADO_GROUP3_DB.COLLECTIBLE_DIECAST.SHIPMENT_MODE(modeID);

-- Constraints for ORDER_DETAILS
ALTER TABLE COLLECTIBLE_DIECAST.ORDER_DETAILS
ADD CONSTRAINT PK_ORDERDETAILS PRIMARY KEY (orderNumber, productCode),  -- Composite primary key (orderNumber, productCode)
ADD CONSTRAINT FK_ORDERNUMBER FOREIGN KEY (orderNumber) REFERENCES COLLECTIBLE_DIECAST.ORDERS(orderNumber),  -- Foreign key referencing ORDERS
ADD CONSTRAINT FK_PRODUCTCODE FOREIGN KEY (productCode) REFERENCES COLLECTIBLE_DIECAST.PRODUCTS(productCode);  -- Foreign key referencing PRODUCTS

-- Constraints for VENDORS
ALTER TABLE COLLECTIBLE_DIECAST.VENDORS 
ADD CONSTRAINT PK_VENDORS PRIMARY KEY (VENDORID);
