-- STANDARDIZE PHONE NUMBERS 

CREATE OR REPLACE TABLE COLLECTIBLE_DIECAST.VENDORS AS   

SELECT   

    	VENDORID, 

    	PRODUCTVENDOR, 

    	CONTACTNAME, 

    	ADDRESS1, 

    	ADDRESS2, 

    	CITY, 

    	STATE, 

    	POSTALCODE, 

    	COUNTRY, 

        REGEXP_REPLACE(PHONE, '[^0-9]', '') AS PHONE 

FROM COLLECTIBLE_DIECAST.VENDORS; 

-- ADD PRIMARY KEY CONSTRAINT
ALTER TABLE COLLECTIBLE_DIECAST.VENDORS 
ADD CONSTRAINT PK_VENDORS PRIMARY KEY (VENDORID);
