name: Snowflake SQL Automation Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  run-sql-scripts:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SnowSQL
        run: |
          # Set the version and download URL for the MSI installer
          $version = "1.3.2"
          $downloadUrl = "https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/$version/windows_x86_64/snowsql-$version-windows_x86_64.msi"

          # Download the MSI installer
          Invoke-WebRequest -Uri $downloadUrl -OutFile "snowsql-installer.msi"

          # Install SnowSQL using the MSI installer
          Start-Process msiexec.exe -ArgumentList '/i', 'snowsql-installer.msi', '/quiet', '/norestart' -Wait

      - name: Set up Snowflake credentials
        run: |
          echo "[connections.default]" > $env:USERPROFILE\.snowsql\config
          echo "accountname = ${SNOWFLAKE_ACCOUNT}" >> $env:USERPROFILE\.snowsql\config
          echo "username = ${SNOWFLAKE_USER}" >> $env:USERPROFILE\.snowsql\config
          echo "password = ${SNOWFLAKE_PASSWORD}" >> $env:USERPROFILE\.snowsql\config
          echo "dbname = ${SNOWFLAKE_DATABASE}" >> $env:USERPROFILE\.snowsql\config
          echo "warehouse = ${SNOWFLAKE_WAREHOUSE}" >> $env:USERPROFILE\.snowsql\config
          echo "schemaname = ${SNOWFLAKE_SCHEMA}" >> $env:USERPROFILE\.snowsql\config

      - name: Run SQL scripts in Snowflake
        run: |
          # Run SQL scripts from the repository
          snowsql -c default -f ./sql/country.sql
          snowsql -c default -f ./sql/customers.sql
          snowsql -c default -f ./sql/facebook_ads.sql
          snowsql -c default -f ./sql/order.sql
          snowsql -c default -f ./sql/order_details.sql
          snowsql -c default -f ./sql/payments.sql
          snowsql -c default -f ./sql/product_reviews.sql
          snowsql -c default -f ./sql/region.sql
          snowsql -c default -f ./sql/vendors.sql
          # Add other SQL scripts here if necessary


