name: Snowflake SQL Automation Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  run-sql-scripts:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SnowSQL (Windows version)
        run: |
          # Define SnowSQL version
          $SNOWSQL_VERSION = "3.12.4"  # Replace with desired version

          # Download SnowSQL installer (Windows .exe)
          Invoke-WebRequest -Uri "https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/$SNOWSQL_VERSION/windows_x86_64/snowsql-$SNOWSQL_VERSION-win_x86_64.exe" -OutFile "snowsql-installer.exe"

          # Install SnowSQL
          Start-Process -FilePath "snowsql-installer.exe" -ArgumentList "/quiet" -Wait

          # Remove installer file
          Remove-Item "snowsql-installer.exe"

      - name: Set up Snowflake credentials
        run: |
          echo "[connections.default]" > $env:USERPROFILE\.snowsql\config
          echo "accountname = ${SNOWFLAKE_ACCOUNT}" >> $env:USERPROFILE\.snowsql\config
          echo "username = ${SNOWFLAKE_USER}" >> $env:USERPROFILE\.snowsql\config
          echo "password = ${SNOWFLAKE_PASSWORD}" >> $env:USERPROFILE\.snowsql\config
          echo "dbname = ${SNOWFLAKE_DATABASE}" >> $env:USERPROFILE\.snowsql\config
          echo "warehouse = ${SNOWFLAKE_WAREHOUSE}" >> $env:USERPROFILE\.snowsql\config
          echo "schemaname = ${SNOWFLAKE_SCHEMA}" >> $env:USERPROFILE\.snowsql\config

      - name: Run SQL scripts in Snowflake
        run: |
          # Run SQL scripts from the repository
          snowsql -c default -f ./sql/country.sql
          snowsql -c default -f ./sql/customers.sql
          snowsql -c default -f ./sql/facebook_ads.sql
          snowsql -c default -f ./sql/order.sql
          snowsql -c default -f ./sql/order_details.sql
          snowsql -c default -f ./sql/payments.sql
          snowsql -c default -f ./sql/product_reviews.sql
          snowsql -c default -f ./sql/region.sql
          snowsql -c default -f ./sql/vendors.sql
          # Add other SQL scripts here if necessary


