name: Snowflake SQL Automation Pipeline

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the main branch

jobs:
  run-sql-scripts:
    runs-on: ubuntu-latest  # Use a Linux-based runner

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SnowSQL
        run: |
          # Check if SnowSQL is already installed
          if ! command -v snowsql &> /dev/null; then
            echo "Downloading SnowSQL installer..."

            # Clean up any existing SnowSQL files
            rm -f snowsql-1.3.2-linux_x86_64.bash

            # Directly download the SnowSQL installer for version 1.3.2 with verbose output
            curl -LO --verbose https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.3/linux_x86_64/snowsql-1.3.2-linux_x86_64.bash

            # Check if the file was downloaded successfully
            if [ ! -f snowsql-1.3.2-linux_x86_64.bash ]; then
              echo "Failed to download SnowSQL installer."
              exit 1
            fi

            # Make the downloaded file executable with verbose logging
            chmod +x snowsql-1.3.2-linux_x86_64.bash

            # Run the SnowSQL installation script with verbose output
            ./snowsql-1.3.2-linux_x86_64.bash --verbose
          else
            echo "SnowSQL is already installed."
          fi

      - name: Set up Snowflake credentials
        run: |
          echo "[connections.default]" > $HOME/.snowsql/config
          echo "accountname = ${SNOWFLAKE_ACCOUNT}" >> $HOME/.snowsql/config
          echo "username = ${SNOWFLAKE_USER}" >> $HOME/.snowsql/config
          echo "password = ${SNOWFLAKE_PASSWORD}" >> $HOME/.snowsql/config
          echo "dbname = ${SNOWFLAKE_DATABASE}" >> $HOME/.snowsql/config
          echo "warehouse = ${SNOWFLAKE_WAREHOUSE}" >> $HOME/.snowsql/config
          echo "schemaname = ${SNOWFLAKE_SCHEMA}" >> $HOME/.snowsql/config

      - name: Run SQL scripts in Snowflake
        run: |
          # Run SQL scripts from the repository
          snowsql -c default -f ./sql/country.sql
          snowsql -c default -f ./sql/customers.sql
          snowsql -c default -f ./sql/facebook_ads.sql
          snowsql -c default -f ./sql/order.sql
          snowsql -c default -f ./sql/order_details.sql
          snowsql -c default -f ./sql/payments.sql
          snowsql -c default -f ./sql/product_reviews.sql
          snowsql -c default -f ./sql/region.sql
          snowsql -c default -f ./sql/vendors.sql
          # Add other SQL scripts here if necessary

